# ----------------------------------------------------------------------------
# GitHub Actions Workflow: Python CI/CD with Docker
# ----------------------------------------------------------------------------

name: Python CI/CD with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# 將 permissions 區塊添加到這裡，與 'on' 和 'env' 同級
permissions:
  contents: read   # 允許 Checkout Action 讀取儲存庫內容
  packages: write  # 允許這個 Workflow 推送 Docker 映像檔到 GitHub Packages (GHCR)

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # 如果只想針對特定 Job 設定權限，可以在 Job 內部添加 permissions:
    # permissions:
    #   contents: read
    #   packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

  build-and-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    # 如果上面已經在 Workflow 級別設定了 permissions，這裡就不需要重複。
    # 但如果 Workflow 級別沒設定，且這個 Job 需要特定權限，可以單獨設定。
    # permissions:
    #   contents: read
    #   packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata for tagging
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Docker image pushed confirmation
        run: |
          echo "Docker image ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }} has been pushed."
          echo "您可以到 GitHub 儲存庫的 'Packages' 頁面查看。"